[2024-07-25T10:47:35.551+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensors_move_file.move_file_task scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2024-07-25T10:47:35.561+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensors_move_file.move_file_task scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2024-07-25T10:47:35.562+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-25T10:47:35.586+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): move_file_task> on 2023-03-22 00:00:00+00:00
[2024-07-25T10:47:35.594+0000] {standard_task_runner.py:57} INFO - Started process 7190 to run task
[2024-07-25T10:47:35.607+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sensors_move_file', 'move_file_task', 'scheduled__2023-03-22T00:00:00+00:00', '--job-id', '1547', '--raw', '--subdir', 'DAGS_FOLDER/move_file/move_file_to_output_dag.py', '--cfg-path', '/tmp/tmp3n8aio1f']
[2024-07-25T10:47:35.608+0000] {standard_task_runner.py:85} INFO - Job 1547: Subtask move_file_task
[2024-07-25T10:47:35.767+0000] {task_command.py:416} INFO - Running <TaskInstance: sensors_move_file.move_file_task scheduled__2023-03-22T00:00:00+00:00 [running]> on host c7799c7b21e5
[2024-07-25T10:47:35.904+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensors_move_file' AIRFLOW_CTX_TASK_ID='move_file_task' AIRFLOW_CTX_EXECUTION_DATE='2023-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-22T00:00:00+00:00'
[2024-07-25T10:47:35.933+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-25T10:47:35.933+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mv $AIRFLOW_HOME/files_to_test/sensors_files/*.json $AIRFLOW_HOME/files_to_test/output_files/']
[2024-07-25T10:47:35.962+0000] {subprocess.py:86} INFO - Output:
[2024-07-25T10:47:36.197+0000] {subprocess.py:93} INFO - mv: cannot stat '/opt/***/files_to_test/sensors_files/*.json': No such file or directory
[2024-07-25T10:47:36.205+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-25T10:47:36.220+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-25T10:47:36.235+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sensors_move_file, task_id=move_file_task, execution_date=20230322T000000, start_date=20240725T104735, end_date=20240725T104736
[2024-07-25T10:47:36.259+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1547 for task move_file_task (Bash command failed. The command returned a non-zero exit code 1.; 7190)
[2024-07-25T10:47:36.314+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-25T10:47:36.347+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:21:26.440+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensors_move_file.move_file_task scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2024-07-25T14:21:26.508+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensors_move_file.move_file_task scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2024-07-25T14:21:26.516+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-25T14:21:26.574+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): move_file_task> on 2023-03-22 00:00:00+00:00
[2024-07-25T14:21:26.672+0000] {standard_task_runner.py:57} INFO - Started process 3295 to run task
[2024-07-25T14:21:26.757+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sensors_move_file', 'move_file_task', 'scheduled__2023-03-22T00:00:00+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/move_file/move_file_to_output_dag.py', '--cfg-path', '/tmp/tmpevcrfmsd']
[2024-07-25T14:21:26.768+0000] {standard_task_runner.py:85} INFO - Job 321: Subtask move_file_task
[2024-07-25T14:21:27.592+0000] {task_command.py:416} INFO - Running <TaskInstance: sensors_move_file.move_file_task scheduled__2023-03-22T00:00:00+00:00 [running]> on host b7334bec8397
[2024-07-25T14:21:29.823+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensors_move_file' AIRFLOW_CTX_TASK_ID='move_file_task' AIRFLOW_CTX_EXECUTION_DATE='2023-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-22T00:00:00+00:00'
[2024-07-25T14:21:29.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-25T14:21:29.825+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mv $AIRFLOW_HOME/files_to_test/sensors_files/*.json $AIRFLOW_HOME/files_to_test/output_files/']
[2024-07-25T14:21:30.399+0000] {subprocess.py:86} INFO - Output:
[2024-07-25T14:21:30.755+0000] {subprocess.py:93} INFO - mv: cannot stat '/opt/***/files_to_test/sensors_files/*.json': No such file or directory
[2024-07-25T14:21:30.756+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-25T14:21:30.819+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-25T14:21:30.897+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sensors_move_file, task_id=move_file_task, execution_date=20230322T000000, start_date=20240725T142126, end_date=20240725T142130
[2024-07-25T14:21:31.143+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 321 for task move_file_task (Bash command failed. The command returned a non-zero exit code 1.; 3295)
[2024-07-25T14:21:31.592+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-25T14:21:31.961+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
